version: '3.8'
services:
    mvc-app:
        build:
            context: .
            dockerfile: DocTrackerMVC.Dockerfile
        ports:
            - "7209:7209"
        environment:
            - ASPNETCORE_URLS=http://+:7209
        depends_on:
            - api-app
        volumes:
            - ./data-protection/mvc:/root/.aspnet/DataProtection-Keys

    api-app:
        build:
            context: .
            dockerfile: DocTrackerWebApi.Dockerfile
        ports:
            - "7293:7293"
        environment:
            - ASPNETCORE_URLS=http://+:7293
        volumes:
            - ./data-protection/api:/root/.aspnet/DataProtection-Keys
